name: deploy
on:
  repository_dispatch:
    types: [deploy]
jobs:
  deploy:
    name: Deploy ${{STAGE}}
    runs-on: ubuntu-latest
    env:
      STAGE: ${{ github.event.client_payload.stage }}
      PROJECT: ${{ github.event.client_payload.project }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Add ssh key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.CI_DEPLOY_KEY }}
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - name: Use Node.js ${{ steps.nvmrc.outputs.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvmrc.outputs.node_version }}
      - name: Install dependencies
        run: yarn install
      - name: Run deploy script
        run: NODE_ENV=${STAGE##*/} yarn deploy:${PROJECT}
